//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daibot.Plugin.OpenAI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daibot.Plugin.OpenAI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 chat 的本地化字符串。
        /// </summary>
        internal static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 create table if not exists story_list (
        ///	name text primary key,
        ///	story text
        ///);
        ///
        ///create table if not exists group_story (
        ///	gid integer primary key,
        ///	story_name text
        ///);
        ///
        ///create table if not exists prompt_rule (
        ///	gid integer default(0),
        ///	name text,
        ///	prompt text,
        ///	rule text,
        ///	constraint prompt_rule_PK primary key(gid,name)
        ///);
        ///
        ///insert into story_list(name,story) values
        ///(&apos;default&apos;,&apos;{AI}是AI聊天助手。他聪明热情。{Info}以下是{AI}与{Human}的对话。&apos;);
        ///
        ///insert into prompt_rule(name,prompt,rule) values
        ///(&apos;父子关系&apos;,&apos;{botN [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitDbSql {
            get {
                return ResourceManager.GetString("InitDbSql", resourceCulture);
            }
        }
    }
}
